name = "ColorSchemeTools"
uuid = "d3e213a1-5e82-5c18-bb32-2a58a99f8c46"
authors = ["cormullion <cormullion@mac.com>"]
version = "1.1.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test"]

[compat]
julia         = "1"
Clustering    = "^0.13"
ColorSchemes  ="^3"
Colors        = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 1.0"
FileIO        = "^1"
Images        = "0.19, 0.20, 0.21, 0.22"
ImageMagick   = "0.7, 1"
QuartzImageIO = "^0.7"
